#!/usr/bin/env bash

FLOWHOME=$HOME/.flow
SCRIPTDIR=$FLOWHOME/flow.d

function main() {
        if [ -d $SCRIPTDIR ] ; then
            local action
            case $1 in
                enter)
                    printf "entering flow\n"
                    action='diminish "$1" &'
                    ;;
                leave)
                    printf "leaving flow\n"
                    action='restore "$1" &'
                    ;;
                *)
                    usage
                    exit 1
                    ;;
            esac

            find -L $HOME/.flow/flow.d -type f -regex '.*/[0-9][0-9][0-9][^/]*' -exec bash -c "$action" inline_sh {} \;
            echo
        fi
}

function usage() {
    cat <<EOF
usage: flow COMMAND

Commands:
  enter    Enter a state of flow by reducing distractions
  leave    Leave a state of flow, restore communications, notifications, etc.
EOF
}

function restore() {
    printf "."
    osascript $1 restore #2>&1 |tr  "[:upper:]" "[:lower:]" |awk '/error/ { printf "x" }'
};export -f restore

function diminish() {
    printf "."
    osascript $1 diminish #2>&1 |tr  "[:upper:]" "[:lower:]" |awk '/error/ { printf "x" }'
};export -f diminish

main $@
